Update armmox

diff --git a/ArmMox/armmox b/ArmMox/armmox
--- a/ArmMox/armmox
+++ b/ArmMox/armmox
@@ -5,6 +5,7 @@
 # License: MIT
 # https://raw.githubusercontent.com/Telxey/Proxmox/main/LICENSE
 
+
 # Colors Codes
  default=`echo -en "\e[39m"`
  UL="\033[4m"
@@ -71,14 +72,14 @@ msg_error() {
 check_root() {
   if [[ "$(id -u)" -ne 0 || $(ps -o comm= -p $PPID) == "sudo" ]]; then
     clear
-    msg_error "The script need to be run as root."
+    msg_error "Please run this script as root."
     echo -e "\nExiting..."
     sleep 2
     exit
   fi
 }
 if ! [ "$(id -u)" = 0 ]; then
-   msg_error "The script need to be run as root." >&2   
+   msg_ok "The script need to be run as root." >&2
    exit 1
 fi
 
@@ -86,6 +87,22 @@ if [ "$SUDO_USER" ]; then
     export real_user=$SUDO_USER
 else
     real_user=$(whoami)
+fi
+OUTPUT=$(cat /etc/*release)
+OS=$(cat /etc/*-release | grep -Po "(?<=^ID=).+" | sed 's/"//g')
+NAME=$(cat /etc/*-release | grep -E "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')
+HS=$(hostname)
+ARCH=$(uname -m)
+LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
+EXT_IP=$(dig @resolver4.opendns.com myip.opendns.com +short)
+if echo "$OUTPUT" | grep -q "Orange Pi" ; then
+                export  SERVER_OS="Orange Pi"
+
+else
+
+                echo -e "${RED}Unable to detect supported OS...${CLE}"
+                echo -e "${WHT}${BOLD}This Install is supported on ${ORG}${BOLD}Orange Pi ${WHT}${BOLD}Distro Only ...${CLE}"
+                exit 1
 fi
 
 clear
@@ -102,44 +119,46 @@ cat <<"EOF"
 EOF
 
 echo -e "${CL}"
+echo -e "${GN}                   User ${RD} ---> ${WHT}${UL}$(whoami)${CL} ${RD}<---${CL}${GRN} running script${CL}"
+echo -e "${GRN}${BOLD}   Supported OS${CLE}${RED} $OS${ORG} $NAME ${LBL}$ARCH  ${GRN}${BOLD}Runimg ${CLE}"
 echo -e "${WHT}${BOLD}   ====================================================================${CL}"
-echo -e "${LBL}       PLEASE DONT USE SUDO, USE SU TO LOGIN TO THE ROOT USER                 ${CL}"
-echo -e "${LBL}    PLEASE STOP THIS SCRIPT NOW WITH CONTROL+C IF YOU ARE USING SUDO          ${CL}"
-echo -e "${LBL}                  CONTINUING SETUP IN 5 SECONDS...                            ${CL}"
+echo -e "${LBL}                  DETECTED ${WHT}${UL}$(whoami)${CL} ${LBL} RUN THIS SCRIPT                    ${CL}"
+echo -e "${LBL}          PLEASE DONT USE${RED} sudo${LBL}, USE${GRN} su ${CL}${LBL}TO LOGIN TO THE ROOT USER  ${CL}"
+echo -e "${LBL}             PLEASE STOP THIS SCRIPT YOU ARE USING SUDO                                        ${CL}"
+echo -e "${LBL}           IF YOU ARE USING SUDO SCRIPT FAIL ON NEXT STEP PLEASE                               ${CL}"
 echo -e "${WHT}${BOLD}   ====================================================================${CL}"
-OUTPUT=$(cat /etc/*release)
-OS=$(cat /etc/*-release | grep -Po "(?<=^ID=).+" | sed 's/"//g')
-NAME=$(cat /etc/*-release | grep -E "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')
-HS=$(hostname)
-ARCH=$(uname -m)
-LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
-EXT_IP=$(dig @resolver4.opendns.com myip.opendns.com +short)
-if echo "$OUTPUT" | grep -q "Orange Pi" ; then
-echo -e " ${GRN}${BOLD}   supported OS${CLE}${RED} $OS${ORG} $NAME ${LBL}$ARCH  ${GRN}${BOLD}Runimg ${CLE}"
-echo -e "${CL}${WHT}Hostname${RED}: ${GRN}$HS ${WHT}Local IP${RED}:${GRN} $LOCAL_IP ${WHT} Eternal IP${RED}: ${GRN}$EXT_IP${CL}"
-              export  SERVER_OS="Orange Pi"
 
-else
-
-                echo -e "${RED}Unable to detect supported OS...${CLE}"
-                echo -e "${WHT}${BOLD}This Install is supported on ${ORG}${BOLD}Orange Pi ${WHT}${BOLD}Distro Only ...${CLE}"
-                exit 1
+echo -e "${CL}${WHT}   Hostname${RED}: ${GRN}$HS ${WHT}Local IP${RED}:${GRN} $LOCAL_IP ${WHT} Eternal IP${RED}: ${GRN}$EXT_IP${CL}"
+echo -e "${CL}"
+#read -r -p "Would you like exit to login as  root now ? ( if you are root hit enter ) <y/N> " prompt
+echo -e "${YLW}Would you like exit to login as  root now ? type y or  if you are root hit ${GN}${UL}ENTER${CL}" 
+read -r -p "Select Yes or No  <y/N> " prompt
+if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
+    echo -e "${GRN}Run ${WHT}${DIM}${BOLD}${UL}su${CLE}${GRN} for switch to ${WHT}${BOLD}root${CLE}"
+    exit 1
 fi
-
+read -r -p "Would you like to add set root Password now ?( If no hit enter ) <y/N> " prompt
+if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
+  sudo passwd root
+fi
+read -r -p "Would you like to change default user --> orangepi <-- Password now ?( If no hit enter ) <y/N> " prompt
+if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
+  sudo passwd orangepi
+fi
 sleep 5
 ###
 #
 #
 # Start collecting system OS
 echo -e "${GRN}${BOLD}Collect some basic information on your system, you appear to be running:${CLE} "
-echo -e "${ORG}"
+echo -e "${YLW}"
 echo -e "          --  OS Name                $(cat /etc/*-release | grep -Po "(?<=^ID=).+" | sed 's/"//g')"
 echo -e "          --  Description            $(cat /etc/*-release | grep -E "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')"
 echo -e "          --  OS Version release     $(cat /etc/*-release | grep -E "VERSION_ID" | cut -d = -f 2 | tr -d '"')"
 echo -e "          --  Code Name              $(cat /etc/*-release | grep -E "VERSION_CODENAME" | cut -d = -f 2 | tr -d '"')"
 echo -e "${CLE}"
 echo -e "${WHT}${BOLD}    --------------------------------------------------------------------${CL}"
-echo -e "${YLW}"
+echo -e "${LBL}"
 cat <<"EOF"
                   Be patient with the installing setup, 
                  take a few minutes depending on PI model
@@ -187,7 +206,30 @@ msg_ok "DONE"
 msg_info "Updating packages list"
 apt update &> /dev/null
 msg_ok "System updateted"
-exit
-orangepi-config
-#sudo apt install ifupdown2 >/dev/null
-#sudo apt install proxmox-ve postfix open-iscsi pve-edk2-firmware-aarch64
+msg__info "Instaling PVE Networking tools"
+#sudo apt install -y ifupdown2  &> /dev/null
+msg_ok "DONE"
+msg_ok "Start Instalations"
+apt install -y proxmox-ve postfix open-iscsi pve-edk2-firmware-aarch64  &> /dev/null
+masg_ok " proxmox Instaled sucess "
+msg_info "Instaling aarch64 tools"
+apt install -y pve-edk2-firmware-aarch64 &> /dev/null
+msg_ok " DONE"
+
+printf "
+=========================================================================================
+                   $GRN     ! INSTALATION COMPLETED ! WAIT ! REBOOT ! $CLE
+=========================================================================================
+
+    after reboot the PVE web interface will be reachable here :
+      --->  $GRN https://$LOCAL_IP:8006/ $CLE <---
+
+    For External access to PVE interface set route to be reachable here :
+      --->  $GRN https://$EXT_IP:8006/ $CLE
+         run ---> $YLW apt upgrade -y $CLE <---
+
+           in a root shell to complete the installation.
+
+\n" && sleep 10 && reboot
+
+#### EOF ####
